@startuml

class DB{
    znajdzZajecia(Przedmiot, Student):Zajecia
    aktualizujZajecia(Zajecia)
    dodajWpis(Wpis)
}

class Osoba{
    Imie 
    Nazwisko
    Pesel
}
class Student{
    NrStudenta
}
class Pracownik{
    IDPracownika
}
class PracownikDydaktyczny{
    wystawOcene(Przedmiot, Student, Ocena):bool
}
class PracownikDziekanatu 
class Dziekan 

class Przedmiot{
    Kod
    Nazwa
}
class Zajecia{
    RokAkad
    Semestr
    'Zastąpione linią
    'Przedmiot : Przedmiot
    listaStucentow() : Student[]
}

class Wpis{
    Ocena
}

Student --|> Osoba 
Osoba <|-- Pracownik
PracownikDziekanatu --|> Pracownik
PracownikDydaktyczny --|> Pracownik
Dziekan --|> Pracownik
PracownikDydaktyczny -up- DB

Wpis "Student" --o "Oceny" Student
Zajecia "Przedmiot" -- Przedmiot
Zajecia "Wpisy" o--left-- "Przedmiot" Wpis

'Powiązanie jest w relacji bazodanowej natomiast nie jest reprezentowane w klasach
'Zajecia "Prowadzacy" --o PracownikDydaktyczny
Zajecia "Studenci" o--o Student


@enduml